### ISSUE TITLE
Add Test-Framework

### ISSUE THREAD

**Issue by XPerianer** [NiklasKoehnecke/DoppelkopfFramework#1]
There should be at least some coverage on the logic that is implementing if moves are correct. 
Also tests can be a great way to document which extra rules are currently supported, and to understand the framework easier.

**Comment by NiklasKoehnecke** [comment]
GTest-Framework only works on Visual Studio compiler (at least for me), tried a while to make it work for MinGW but failed. So that would be a tradeoff

**Comment by XPerianer** [comment]
Make a pull request for it and I will look if it works for me

**Comment by schonacin** [comment]
Great talk guys
