### ISSUE TITLE
Improve cmakelists.txt

### ISSUE THREAD

**Issue by benrobby** [NiklasKoehnecke/DoppelkopfFramework#7]
- [ ] specify c++ standard (maybe 14?)
- [ ] use lower cmake version if you dont explicitly need a higher one (need <= 3.8 for compatibility reasons)
- [x] specify out of source build dir so the relative paths work

**Comment by XPerianer** [comment]
1 and 2 are closed with #9 , and 3 is local configuration of you cmake.
